# Setup
title: Blog
tagline: ''
baseurl: ''
paginate: 1
locale: 'en'

# About/contact
author:
  name: oneybee
  url: https://oneybee.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman